#!/usr/bin/env bash
#
# Installs terminal-dotnet as a command on PATH.
#
#   ./install.sh                 install into ~/.local
#   ./install.sh --uninstall     remove it again
#   ./install.sh --prefix DIR    install into DIR instead
#   ./install.sh --self-contained
#                                bundle the .NET runtime, so the install
#                                survives the SDK it was built with going away
#
set -euo pipefail

readonly COMMAND_NAME="terminal-dotnet"
readonly PROJECT="src/TerminalDotnet/TerminalDotnet.csproj"
readonly ASSEMBLY="TerminalDotnet"

prefix="${PREFIX:-$HOME/.local}"
self_contained="false"
action="install"

usage() {
    sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; $d'
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --uninstall) action="uninstall"; shift ;;
        --self-contained) self_contained="true"; shift ;;
        --prefix) prefix="${2:?--prefix needs a directory}"; shift 2 ;;
        --prefix=*) prefix="${1#--prefix=}"; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    esac
done

readonly source_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly bin_dir="$prefix/bin"
readonly install_dir="$prefix/libexec/$COMMAND_NAME"
readonly shim="$bin_dir/$COMMAND_NAME"

if [ "$action" = "uninstall" ]; then
    rm -f -- "$shim"
    rm -rf -- "$install_dir"
    echo "Removed $shim and $install_dir"
    exit 0
fi

command -v dotnet >/dev/null 2>&1 || {
    echo "dotnet was not found on PATH. Install the .NET SDK first." >&2
    exit 1
}

publish_args=(--configuration Release --output "$install_dir.staging")
if [ "$self_contained" = "true" ]; then
    publish_args+=(--self-contained true --runtime "$(dotnet --info |
        sed -n 's/^ *RID: *//p' | head -n 1)")
fi

echo "Publishing $COMMAND_NAME..."
rm -rf -- "$install_dir.staging"
dotnet publish "$source_dir/$PROJECT" -m:1 "${publish_args[@]}"

[ -x "$install_dir.staging/$ASSEMBLY" ] || {
    echo "Publish did not produce $install_dir.staging/$ASSEMBLY" >&2
    rm -rf -- "$install_dir.staging"
    exit 1
}

mkdir -p -- "$bin_dir" "$(dirname -- "$install_dir")"
rm -rf -- "$install_dir"
mv -- "$install_dir.staging" "$install_dir"

cat > "$shim" <<SHIM
#!/usr/bin/env bash
# Generated by terminal-dotnet/install.sh. Runs in the caller's directory,
# which is the repository terminal-dotnet inspects.
exec "$install_dir/$ASSEMBLY" "\$@"
SHIM
chmod +x -- "$shim"

echo
echo "Installed $COMMAND_NAME to $shim"

case ":$PATH:" in
    *":$bin_dir:"*) echo "Run '$COMMAND_NAME' from any .NET repository." ;;
    *) echo "Add $bin_dir to PATH to use it:"
       echo "    export PATH=\"$bin_dir:\$PATH\"" ;;
esac
